name: 🪴 Generate POT File
description: Generate a POT file from the plugin source code

inputs:
    plugin_path:
        description: 'The path to the plugin source code. Used to search for files to translate.'
        required: true
    pot_path:
        description: 'The path to the POT file to sync'
        required: true

runs:
    using: "composite"
    steps:
        -   name: Install npm dependencies & build for translation
            shell: bash
            run: |
                npm install -g npm@7
                npm ci
                npm run build # Must be built for production before generating POT file.

        -   name: Generate POT file
            shell: bash
            run: |
                curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
                chmod +x wp-cli.phar
                mv wp-cli.phar /usr/local/bin/wp
                php -d xdebug.mode=off "$(which wp)" i18n make-pot ${{ inputs.plugin_path }} ${{ inputs.pot_path }} --exclude="$(cat .distignore | tr "\n" "," | sed 's/,$/ /' | tr " " "\n"),src/*.js,src/**/*.js,blocks/**/*.js"
