name: Static Analysis

on:
    push:
    pull_request:
    workflow_call: # Allows you to use this workflow as part of another workflow
    workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
    analyse:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ 7.0, 7.4, 8.0 ]

        steps:
            -   uses: actions/checkout@v3
            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                    coverage: none

            -   name: Install composer dependencies + PHPStan and extensions
                run: composer install --no-dev --no-scripts --no-progress --no-interaction
                    

            -   name: Set up PHP for PHPStan
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                    coverage: none

            -   name: Install composer dependencies + PHPStan and extensions
                run: |
                    composer config platform.php ${{ matrix.php }}
                    composer require phpstan/phpstan szepeviktor/phpstan-wordpress:1.1.3 timeweb/phpstan-enum --ignore-platform-reqs --no-scripts --no-progress --no-interaction

            -   name: Analyse
                run: php -d memory_limit=-1 vendor/bin/phpstan analyse -c phpstan.neon
