name: Static Analysis

on:
    push:
    pull_request:
    workflow_call: # Allows you to use this workflow as part of another workflow
    workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
    analyse:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ 7.2, 7.4, 8.0 ]

        steps:
            -   uses: actions/checkout@v3
            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                    coverage: none

            -   name: Install composer dependencies
                run: composer install --ignore-platform-reqs --no-progress --no-interaction

            -   name: Install PHPStan and extensions
                run: composer require --dev phpstan/phpstan szepeviktor/phpstan-wordpress:1.1.3 timeweb/phpstan-enum --ignore-platform-reqs --no-progress --no-interaction

            -   name: Analyse
                run: php -d memory_limit=-1 vendor/bin/phpstan analyse -c phpstan.neon
