name: 🔁 Sync Translations

on:
    workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
        inputs:
            ref:
                description: 'Git Commit Ref (branch, tag, or hash)'
                required: true
                type: string
                default: 'master'
            plugin_slug:
                description: 'Plugin Slug'
                required: true
                type: string
    workflow_call:
        inputs:
            ref:
                description: 'Git Commit Ref (branch, tag, or hash)'
                required: true
                type: string
                default: 'master'
            plugin_slug:
                description: 'Plugin Slug'
                required: true
                type: string

jobs:
    setup-environment:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ inputs.ref }}

            -   name: Install composer dependencies
                uses: php-actions/composer@v6
                if: ${{ inputs.install_composer_packages }}
                with:
                    php_version: 7.4
                    dev: no

            -   uses: actions/setup-node@v1
                with:
                    node-version: '12'

            -   name: Install npm dependencies & build for translation
                run: |
                    npm install -g npm@7
                    npm ci
                    npm run dev

    generate-pot:
        uses: impress-org/givewp-github-actions/.github/workflows/generate-pot.yml@master
        with:
            ref: ${{ inputs.ref }}
            plugin_slug: ${{ inputs.plugin_slug }}

    sync-translations:
        runs-on: ubuntu-latest

        steps:
            -   name: Deploy POT file to translations.stellarwp.com
                uses: burnett01/rsync-deployments@4.1
                with:
                    plugin_slug: ${{ inputs.plugin_slug }}
                    switches: -avz --omit-dir-times --no-perms
                    path: languages/${{ inputs.plugin_slug }}.pot
                    remote_path: ${{ secrets.TRANSLATIONS_DEPLOY_POT_LOCATION }}${{ inputs.plugin_slug }}/
                    remote_host: ${{ secrets.TRANSLATIONS_DEPLOY_HOST }}
                    remote_user: ${{ secrets.TRANSLATIONS_DEPLOY_USER }}
                    remote_key: ${{ secrets.TRANSLATIONS_DEPLOY_SSH_KEY }}

            -   name: SSH to Translations StellarWP Website
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.TRANSLATIONS_DEPLOY_HOST }}
                    username: ${{ secrets.TRANSLATIONS_DEPLOY_USER }}
                    key: ${{ secrets.TRANSLATIONS_DEPLOY_SSH_KEY }}
                    script: |
                        pwd
                        cd translations.stellarwp.com/html/
                        wp glotpress import-originals give/${{ inputs.plugin_slug }} ${{ secrets.TRANSLATIONS_DEPLOY_POT_LOCATION }}${{ inputs.plugin_slug }}/${{ inputs.plugin_slug }}.pot
