name: 🔁 Sync Translations

on:
    workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
        inputs:
            ref:
                description: 'Git Commit Ref (branch, tag, or hash)'
                required: true
                type: string
                default: 'master'
            plugin_slug:
                description: 'Plugin Slug'
                required: true
                type: string
    workflow_call:
        inputs:
            ref:
                description: 'Git Commit Ref (branch, tag, or hash)'
                required: true
                type: string
                default: 'master'
            plugin_slug:
                description: 'Plugin Slug'
                required: true
                type: string

jobs:
    sync-translations:
        name: 🔁 Sync Translations
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ inputs.ref }}

            -   name: Install composer dependencies
                uses: php-actions/composer@v6
                if: ${{ inputs.install_composer_packages }}
                with:
                    php_version: 7.4
                    dev: no

            -   uses: actions/setup-node@v3
                with:
                    node-version: '12'

            -   uses: impress-org/givewp-github-actions/.github/actions/generate-pot-file@master
                with:
                    plugin_path: ${{ github.workspace }}
                    pot_path: ${{github.workspace}}/languages/${{ inputs.plugin_slug }}.pot

            -   name: Deploy POT file to translations.stellarwp.com
                uses: burnett01/rsync-deployments@4.1
                with:
                    switches: -avz --omit-dir-times --no-perms
                    path: languages/${{ inputs.plugin_slug }}.pot
                    remote_path: ${{ secrets.TRANSLATIONS_DEPLOY_POT_LOCATION }}givewp/
                    remote_host: ${{ secrets.TRANSLATIONS_DEPLOY_HOST }}
                    remote_user: ${{ secrets.TRANSLATIONS_DEPLOY_USER }}
                    remote_key: ${{ secrets.TRANSLATIONS_DEPLOY_SSH_KEY }}

            -   name: SSH to Translations StellarWP Website
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.TRANSLATIONS_DEPLOY_HOST }}
                    username: ${{ secrets.TRANSLATIONS_DEPLOY_USER }}
                    key: ${{ secrets.TRANSLATIONS_DEPLOY_SSH_KEY }}
                    script: |
                        pwd
                        cd translations.stellarwp.com/html/
                        wp glotpress import-originals givewp/${{ inputs.plugin_slug }} ${{ secrets.TRANSLATIONS_DEPLOY_POT_LOCATION }}givewp/${{ inputs.plugin_slug }}.pot
